{{ $releaseName := .Release.Name }}
{{- range $key, $topic := .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  labels:
    strimzi.io/cluster: {{ $releaseName }}
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  config:
    retention.ms: {{ $topic.retentionMs }}
    segment.bytes: {{ $topic.segmentBytes }}
---
{{ end }}